export const AuditAction = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',
  ADMIN_USER_CREATE: 'ADMIN_USER_CREATE',
  ADMIN_USER_UPDATE: 'ADMIN_USER_UPDATE',
  ADMIN_USER_BLOCK: 'ADMIN_USER_BLOCK',
  ADMIN_USER_UNBLOCK: 'ADMIN_USER_UNBLOCK',
  ADMIN_PASSWORD_REGEN: 'ADMIN_PASSWORD_REGEN',
  ADMIN_PLAN_CHANGE: 'ADMIN_PLAN_CHANGE',
  FEATURE_AI_ANALYZE: 'FEATURE_AI_ANALYZE',
  FEATURE_CHECKOUT: 'FEATURE_CHECKOUT',
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
} as const;

export type AuditActionName = (typeof AuditAction)[keyof typeof AuditAction];
